import { defineManifest, type DriverManifest } from "@supreme/driver-sdk";
import { DEFAULT_DRIVER_OPERATIONS, type DriverConfigField } from "@supreme/domain-model";

/**
 * First-party driver manifests (§9). Each declares a Supreme capability manifest, a config SCHEMA
 * (so the Driver Manager auto-generates its config page), and the operations it supports — so any
 * driver, current or future, appears in the UI automatically with the right controls. A future
 * native rewrite is a drop-in replacement behind the same manifest.
 *
 * Matter ships DISABLED — enabled on demand by the owner/installer (opt-in), runs on the hub.
 */
const PUBLISHER = "Supreme Domotics";

/** Protocol drivers additionally support live connect/disconnect. */
const PROTO_OPS = [...DEFAULT_DRIVER_OPERATIONS, "connect", "disconnect"] as const;

const hostField: DriverConfigField = { key: "host", label: "Gateway host / IP", type: "host", required: true, placeholder: "192.168.1.10", secret: false };
const portField = (def: number): DriverConfigField => ({ key: "port", label: "Port", type: "port", required: true, default: def, secret: false });

export const FIRST_PARTY_MANIFESTS: DriverManifest[] = [
  defineManifest({
    key: "supreme-knx",
    name: "Supreme KNX",
    description: "KNX/EIB bus — lighting, shades, climate.",
    category: "protocol",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["onoff", "brightness", "position", "temperature"],
    protocols: ["knx"],
    compat: { hubMinVersion: "0.1.0", requiresSku: "pro" },
    backend: { type: "native", ref: "knx" },
    operations: [...PROTO_OPS],
    configSchema: [
      hostField,
      portField(3671),
      { key: "individualAddress", label: "Physical address", type: "text", placeholder: "1.1.255", help: "The interface's KNX individual address.", secret: false },
    ],
  }),
  defineManifest({
    key: "supreme-casambi",
    name: "Supreme Casambi",
    description: "Casambi Bluetooth lighting control.",
    category: "lighting",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["onoff", "brightness", "color"],
    protocols: ["casambi"],
    compat: { hubMinVersion: "0.1.0", requiresSku: "pro" },
    backend: { type: "ha-integration", ref: "casambi" },
    operations: [...PROTO_OPS],
    configSchema: [
      { key: "network", label: "Network name", type: "text", required: true, secret: false },
      { key: "apiKey", label: "API key", type: "password", required: true, secret: true },
      { key: "email", label: "Casambi account email", type: "text", secret: false },
    ],
  }),
  defineManifest({
    key: "supreme-dali",
    name: "Supreme DALI",
    description: "DALI-2 lighting buses.",
    category: "lighting",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["onoff", "brightness"],
    protocols: ["dali"],
    compat: { hubMinVersion: "0.1.0", requiresSku: "pro" },
    backend: { type: "native", ref: "dali" },
    operations: [...PROTO_OPS],
    configSchema: [hostField, portField(23), { key: "line", label: "DALI line", type: "number", default: 0, min: 0, max: 15, secret: false }],
  }),
  defineManifest({
    key: "supreme-zigbee",
    name: "Supreme Zigbee",
    description: "Zigbee mesh for sensors, lights, and switches.",
    category: "protocol",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["onoff", "brightness", "color", "sensor"],
    protocols: ["zigbee"],
    compat: { hubMinVersion: "0.1.0", requiresSku: null },
    backend: { type: "native", ref: "zha" },
    operations: [...PROTO_OPS],
    configSchema: [
      { key: "serialPort", label: "Coordinator serial port", type: "text", required: true, placeholder: "/dev/ttyUSB0", secret: false },
      { key: "channel", label: "Zigbee channel", type: "number", default: 15, min: 11, max: 26, secret: false },
      { key: "permitJoin", label: "Permit join (pairing)", type: "boolean", default: false, secret: false },
    ],
  }),
  defineManifest({
    key: "supreme-mqtt",
    name: "Supreme MQTT",
    description: "Generic MQTT device bridge.",
    category: "protocol",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["onoff", "brightness", "sensor"],
    protocols: ["mqtt"],
    compat: { hubMinVersion: "0.1.0", requiresSku: null },
    backend: { type: "native", ref: "mqtt" },
    operations: [...PROTO_OPS],
    configSchema: [
      { key: "url", label: "Broker URL", type: "text", required: true, placeholder: "mqtt://192.168.1.10:1883", secret: false },
      { key: "username", label: "Username", type: "text", secret: false },
      { key: "password", label: "Password", type: "password", secret: true },
      { key: "baseTopic", label: "Base topic", type: "text", default: "supreme", secret: false },
    ],
  }),
  defineManifest({
    key: "supreme-modbus",
    name: "Supreme Modbus",
    description: "Modbus TCP/RTU for energy and HVAC plant.",
    category: "energy",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["sensor", "onoff", "temperature"],
    protocols: ["modbus"],
    compat: { hubMinVersion: "0.1.0", requiresSku: "pro" },
    backend: { type: "native", ref: "modbus" },
    operations: [...PROTO_OPS],
    configSchema: [hostField, portField(502), { key: "unitId", label: "Unit / slave id", type: "number", default: 1, min: 1, max: 247, secret: false }],
  }),
  defineManifest({
    key: "supreme-matter",
    name: "Supreme Matter",
    description: "Local Matter controller — opt-in, runs entirely on the hub.",
    category: "protocol",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["onoff", "brightness", "color", "position", "sensor"],
    protocols: ["matter"],
    compat: { hubMinVersion: "0.1.0", requiresSku: null },
    backend: { type: "native", ref: "matter" },
    shipsDisabled: true,
    operations: [...PROTO_OPS],
    configSchema: [{ key: "fabricLabel", label: "Fabric label", type: "text", default: "Supreme", secret: false }],
  }),
  defineManifest({
    key: "supreme-lutron",
    name: "Supreme Lutron",
    description: "Lutron RadioRA 2 / HomeWorks QS / Caséta (Integration Protocol).",
    category: "lighting",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["onoff", "brightness", "position"],
    protocols: ["lutron"],
    compat: { hubMinVersion: "0.1.0", requiresSku: "pro" },
    backend: { type: "native", ref: "lutron" },
    operations: [...PROTO_OPS],
    configSchema: [
      hostField,
      portField(23),
      { key: "username", label: "Integration username", type: "text", default: "lutron", secret: false },
      { key: "password", label: "Integration password", type: "password", default: "integration", secret: true },
    ],
  }),
  defineManifest({
    key: "supreme-coolmaster",
    name: "Supreme CoolMaster",
    description: "CoolAutomation CoolMasterNet — VRF/VRV air-conditioning bridge.",
    category: "climate",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["onoff", "temperature"],
    protocols: ["coolmaster"],
    compat: { hubMinVersion: "0.1.0", requiresSku: "pro" },
    backend: { type: "native", ref: "coolmaster" },
    operations: [...PROTO_OPS],
    configSchema: [hostField, portField(10102)],
  }),
  defineManifest({
    key: "supreme-home-assistant",
    name: "Supreme Home Assistant",
    description: "Bridge an existing Home Assistant instance's entities into Supreme.",
    category: "other",
    channel: "official",
    publisher: PUBLISHER,
    version: "1.0.0",
    capabilities: ["onoff", "brightness", "color", "temperature", "position", "sensor"],
    protocols: [],
    compat: { hubMinVersion: "0.1.0", requiresSku: null },
    backend: { type: "ha-integration", ref: "core" },
    operations: [...PROTO_OPS],
    configSchema: [
      { key: "url", label: "Home Assistant URL", type: "text", required: true, placeholder: "http://homeassistant.local:8123", secret: false },
      { key: "token", label: "Long-lived access token", type: "password", required: true, secret: true },
    ],
  }),
];
